# Generated by Django 4.2.4 on 2023-08-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Adwait_Sarnobat", models.SmallIntegerField(help_text="Contribution")),
                ("Amod_Narhari", models.SmallIntegerField(help_text="Contribution")),
                ("Ankit", models.SmallIntegerField(help_text="Contribution")),
                ("Arun", models.SmallIntegerField(help_text="Contribution")),
                ("Chirag", models.SmallIntegerField(help_text="Contribution")),
                ("Date", models.SmallIntegerField(help_text="Contribution")),
                ("Dilip_Mahajan", models.SmallIntegerField(help_text="Contribution")),
                ("Durgesh_Patil", models.SmallIntegerField(help_text="Contribution")),
                ("Jayant_Wani", models.SmallIntegerField(help_text="Contribution")),
                ("Kunal_Aswale", models.SmallIntegerField(help_text="Contribution")),
                (
                    "Neelang_Chaturvedi",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Nikhil_Kadukar", models.SmallIntegerField(help_text="Contribution")),
                ("Niraj_Gadhe", models.SmallIntegerField(help_text="Contribution")),
                ("Omkar_Panda", models.SmallIntegerField(help_text="Contribution")),
                ("Prasad", models.SmallIntegerField(help_text="Contribution")),
                ("Prem_Jadhav", models.SmallIntegerField(help_text="Contribution")),
                ("Rahul_Dhokale", models.SmallIntegerField(help_text="Contribution")),
                ("Rajesh_Sharma", models.SmallIntegerField(help_text="Contribution")),
                (
                    "Ritesh_Chambhare",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Sahil", models.SmallIntegerField(help_text="Contribution")),
                ("Sameer_Shewale", models.SmallIntegerField(help_text="Contribution")),
                ("Satheesh", models.SmallIntegerField(help_text="Contribution")),
                (
                    "Shanmukha_Vardhan",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                (
                    "Shounak_Deshpande",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Shreekant", models.SmallIntegerField(help_text="Contribution")),
                ("Souvik", models.SmallIntegerField(help_text="Contribution")),
                ("Sujit", models.SmallIntegerField(help_text="Contribution")),
                ("Tuahar", models.SmallIntegerField(help_text="Contribution")),
                ("Umesh", models.SmallIntegerField(help_text="Contribution")),
                ("Vaibhav_Sonar", models.SmallIntegerField(help_text="Contribution")),
                ("Varun", models.SmallIntegerField(help_text="Contribution")),
                ("Vijay_Pal", models.SmallIntegerField(help_text="Contribution")),
                ("Vinit", models.SmallIntegerField(help_text="Contribution")),
                ("Vinod_Hiwale", models.SmallIntegerField(help_text="Contribution")),
            ],
            options={
                "verbose_name_plural": "Weekly Attendance",
            },
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Adwait_Sarnobat", models.SmallIntegerField(help_text="Balance")),
                ("Amod_Narhari", models.SmallIntegerField(help_text="Balance")),
                ("Ankit", models.SmallIntegerField(help_text="Balance")),
                ("Arun", models.SmallIntegerField(help_text="Balance")),
                ("Chirag", models.SmallIntegerField(help_text="Balance")),
                ("Date", models.SmallIntegerField(help_text="Balance")),
                ("Dilip_Mahajan", models.SmallIntegerField(help_text="Balance")),
                ("Durgesh_Patil", models.SmallIntegerField(help_text="Balance")),
                ("Jayant_Wani", models.SmallIntegerField(help_text="Balance")),
                ("Kunal_Aswale", models.SmallIntegerField(help_text="Balance")),
                ("Neelang_Chaturvedi", models.SmallIntegerField(help_text="Balance")),
                ("Nikhil_Kadukar", models.SmallIntegerField(help_text="Balance")),
                ("Niraj_Gadhe", models.SmallIntegerField(help_text="Balance")),
                ("Omkar_Panda", models.SmallIntegerField(help_text="Balance")),
                ("Prasad", models.SmallIntegerField(help_text="Balance")),
                ("Prem_Jadhav", models.SmallIntegerField(help_text="Balance")),
                ("Rahul_Dhokale", models.SmallIntegerField(help_text="Balance")),
                ("Rajesh_Sharma", models.SmallIntegerField(help_text="Balance")),
                ("Ritesh_Chambhare", models.SmallIntegerField(help_text="Balance")),
                ("Sahil", models.SmallIntegerField(help_text="Balance")),
                ("Sameer_Shewale", models.SmallIntegerField(help_text="Balance")),
                ("Satheesh", models.SmallIntegerField(help_text="Balance")),
                ("Shanmukha_Vardhan", models.SmallIntegerField(help_text="Balance")),
                ("Shounak_Deshpande", models.SmallIntegerField(help_text="Balance")),
                ("Shreekant", models.SmallIntegerField(help_text="Balance")),
                ("Souvik", models.SmallIntegerField(help_text="Balance")),
                ("Sujit", models.SmallIntegerField(help_text="Balance")),
                ("Tuahar", models.SmallIntegerField(help_text="Balance")),
                ("Umesh", models.SmallIntegerField(help_text="Balance")),
                ("Vaibhav_Sonar", models.SmallIntegerField(help_text="Balance")),
                ("Varun", models.SmallIntegerField(help_text="Balance")),
                ("Vijay_Pal", models.SmallIntegerField(help_text="Balance")),
                ("Vinit", models.SmallIntegerField(help_text="Balance")),
                ("Vinod_Hiwale", models.SmallIntegerField(help_text="Balance")),
            ],
            options={
                "verbose_name_plural": "Current Balance",
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club",
                    models.CharField(help_text="Favorite Club / Team", max_length=30),
                ),
            ],
            options={
                "verbose_name_plural": "Club",
            },
        ),
        migrations.CreateModel(
            name="FieldPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(help_text="Field Position", max_length=20),
                ),
            ],
            options={
                "verbose_name_plural": "Field Position",
            },
        ),
        migrations.CreateModel(
            name="Foot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foot", models.CharField(help_text="Preferred Foot", max_length=10)),
            ],
            options={
                "verbose_name_plural": "Preferred Foot",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.CharField(
                        help_text="Favorite Football Player", max_length=30
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Player",
            },
        ),
        migrations.CreateModel(
            name="Proficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pro_level",
                    models.CharField(
                        help_text="Beginner, Intermediate or Expert", max_length=20
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Proficiency Level",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="First Name", max_length=100, null=True
                    ),
                ),
                ("last_name", models.CharField(help_text="Last Name", max_length=100)),
                ("image", models.ImageField(upload_to="upload/")),
                ("number", models.SmallIntegerField(help_text="Squad Number")),
                (
                    "favorite_club",
                    models.ForeignKey(
                        help_text="Favorite Club",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_club",
                        to="members.club",
                    ),
                ),
                (
                    "favorite_player",
                    models.ForeignKey(
                        help_text="Favorite Player",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_player",
                        to="members.player",
                    ),
                ),
                (
                    "football_proficiency",
                    models.ForeignKey(
                        help_text="Football Skill Level",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="football_proficiency",
                        to="members.proficiency",
                    ),
                ),
                (
                    "preferred_field_position",
                    models.ForeignKey(
                        help_text="Preferred field position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_field_position",
                        to="members.fieldposition",
                    ),
                ),
                (
                    "preferred_foot",
                    models.ForeignKey(
                        help_text="Preferred Foot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_foot",
                        to="members.foot",
                    ),
                ),
                (
                    "secondary_field_position",
                    models.ForeignKey(
                        help_text="Secondary field position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_field_position",
                        to="members.fieldposition",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Weekend Warriors Member List",
            },
        ),
    ]
