# Generated by Django 4.2.4 on 2023-08-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club",
                    models.CharField(help_text="Favorite Club / Team", max_length=30),
                ),
            ],
            options={
                "verbose_name_plural": "Club",
            },
        ),
        migrations.CreateModel(
            name="FieldPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(help_text="Field Position", max_length=20),
                ),
            ],
            options={
                "verbose_name_plural": "Field Position",
            },
        ),
        migrations.CreateModel(
            name="Foot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foot", models.CharField(help_text="Preferred Foot", max_length=10)),
            ],
            options={
                "verbose_name_plural": "Preferred Foot",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.CharField(
                        help_text="Favorite Football Player", max_length=30
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Player",
            },
        ),
        migrations.CreateModel(
            name="Proficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pro_level",
                    models.CharField(
                        help_text="Beginner, Intermediate or Expert", max_length=20
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Proficiency Level",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="First Name", max_length=100, null=True
                    ),
                ),
                ("last_name", models.CharField(help_text="Last Name", max_length=100)),
                ("image", models.ImageField(upload_to="upload/")),
                ("number", models.SmallIntegerField(help_text="Squad Number")),
                (
                    "favorite_club",
                    models.ForeignKey(
                        help_text="Favorite Club",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_club",
                        to="members.club",
                    ),
                ),
                (
                    "favorite_player",
                    models.ForeignKey(
                        help_text="Favorite Player",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_player",
                        to="members.player",
                    ),
                ),
                (
                    "football_proficiency",
                    models.ForeignKey(
                        help_text="Football Skill Level",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="football_proficiency",
                        to="members.proficiency",
                    ),
                ),
                (
                    "preferred_field_position",
                    models.ForeignKey(
                        help_text="Preferred field position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_field_position",
                        to="members.fieldposition",
                    ),
                ),
                (
                    "preferred_foot",
                    models.ForeignKey(
                        help_text="Preferred Foot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_foot",
                        to="members.foot",
                    ),
                ),
                (
                    "secondary_field_position",
                    models.ForeignKey(
                        help_text="Secondary field position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_field_position",
                        to="members.fieldposition",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Weekend Warriors Member List",
            },
        ),
    ]
