# Generated by Django 4.2.4 on 2023-08-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="image",
            field=models.ImageField(upload_to="media/upload/"),
        ),
        migrations.AlterField(
            model_name="member",
            name="number",
            field=models.SmallIntegerField(help_text="Squad Number"),
        ),
    ]
