# Generated by Django 4.2.4 on 2023-08-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("Nikhil_Kadukar", models.SmallIntegerField(help_text="Contribution")),
                ("Rajesh_Sharma", models.SmallIntegerField(help_text="Contribution")),
                ("Omkar_Panda", models.SmallIntegerField(help_text="Contribution")),
                ("Vinod_Hiwale", models.SmallIntegerField(help_text="Contribution")),
                ("Satheesh", models.SmallIntegerField(help_text="Contribution")),
                ("Varun", models.SmallIntegerField(help_text="Contribution")),
                ("Niraj_Gadhe", models.SmallIntegerField(help_text="Contribution")),
                (
                    "Ritesh_Chambhare",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Prasad", models.SmallIntegerField(help_text="Contribution")),
                ("Jayant_Wani", models.SmallIntegerField(help_text="Contribution")),
                (
                    "Neelang_Chaturvedi",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Durgesh_Patil", models.SmallIntegerField(help_text="Contribution")),
                ("Vinit", models.SmallIntegerField(help_text="Contribution")),
                (
                    "M_Shanmukha_Vardhan",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Rahul_Dhokale", models.SmallIntegerField(help_text="Contribution")),
                ("Amod_Narhari", models.SmallIntegerField(help_text="Contribution")),
                ("Kunal_Aswale", models.SmallIntegerField(help_text="Contribution")),
                ("Sameer_Shewale", models.SmallIntegerField(help_text="Contribution")),
                ("Umesh", models.SmallIntegerField(help_text="Contribution")),
                ("Ankit", models.SmallIntegerField(help_text="Contribution")),
                ("Vaibhav_Sonar", models.SmallIntegerField(help_text="Contribution")),
                ("Prem_Jadhav", models.SmallIntegerField(help_text="Contribution")),
                ("Chirag_Shanmukh", models.SmallIntegerField(help_text="Contribution")),
                ("Sahil", models.SmallIntegerField(help_text="Contribution")),
                ("Dilip_Mahajan", models.SmallIntegerField(help_text="Contribution")),
                ("Arun", models.SmallIntegerField(help_text="Contribution")),
                ("Souvik", models.SmallIntegerField(help_text="Contribution")),
                ("Tuahar", models.SmallIntegerField(help_text="Contribution")),
                ("Vijay_Pal", models.SmallIntegerField(help_text="Contribution")),
                ("Sujit", models.SmallIntegerField(help_text="Contribution")),
                (
                    "Shounak_Deshpande",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Adwait_Sarnobat", models.SmallIntegerField(help_text="Contribution")),
                ("Shreekant", models.SmallIntegerField(help_text="Contribution")),
            ],
            options={
                "verbose_name_plural": "Weekly Attendance",
            },
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("Nikhil_Kadukar", models.SmallIntegerField(help_text="Contribution")),
                ("Rajesh_Sharma", models.SmallIntegerField(help_text="Contribution")),
                ("Omkar_Panda", models.SmallIntegerField(help_text="Contribution")),
                ("Vinod_Hiwale", models.SmallIntegerField(help_text="Contribution")),
                ("Satheesh", models.SmallIntegerField(help_text="Contribution")),
                ("Varun", models.SmallIntegerField(help_text="Contribution")),
                ("Niraj_Gadhe", models.SmallIntegerField(help_text="Contribution")),
                (
                    "Ritesh_Chambhare",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Prasad", models.SmallIntegerField(help_text="Contribution")),
                ("Jayant_Wani", models.SmallIntegerField(help_text="Contribution")),
                (
                    "Neelang_Chaturvedi",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Durgesh_Patil", models.SmallIntegerField(help_text="Contribution")),
                ("Vinit", models.SmallIntegerField(help_text="Contribution")),
                (
                    "M_Shanmukha_Vardhan",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Rahul_Dhokale", models.SmallIntegerField(help_text="Contribution")),
                ("Amod_Narhari", models.SmallIntegerField(help_text="Contribution")),
                ("Kunal_Aswale", models.SmallIntegerField(help_text="Contribution")),
                ("Sameer_Shewale", models.SmallIntegerField(help_text="Contribution")),
                ("Umesh", models.SmallIntegerField(help_text="Contribution")),
                ("Ankit", models.SmallIntegerField(help_text="Contribution")),
                ("Vaibhav_Sonar", models.SmallIntegerField(help_text="Contribution")),
                ("Prem_Jadhav", models.SmallIntegerField(help_text="Contribution")),
                ("Chirag_Shanmukh", models.SmallIntegerField(help_text="Contribution")),
                ("Sahil", models.SmallIntegerField(help_text="Contribution")),
                ("Dilip_Mahajan", models.SmallIntegerField(help_text="Contribution")),
                ("Arun", models.SmallIntegerField(help_text="Contribution")),
                ("Souvik", models.SmallIntegerField(help_text="Contribution")),
                ("Tuahar", models.SmallIntegerField(help_text="Contribution")),
                ("Vijay_Pal", models.SmallIntegerField(help_text="Contribution")),
                ("Sujit", models.SmallIntegerField(help_text="Contribution")),
                (
                    "Shounak_Deshpande",
                    models.SmallIntegerField(help_text="Contribution"),
                ),
                ("Adwait_Sarnobat", models.SmallIntegerField(help_text="Contribution")),
                ("Shreekant", models.SmallIntegerField(help_text="Contribution")),
            ],
            options={
                "verbose_name_plural": "Weekly Balance",
            },
        ),
    ]
