# Generated by Django 4.2.4 on 2023-08-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="Date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="balance",
            name="Date",
            field=models.DateField(unique=True),
        ),
    ]
