# Generated by Django 4.2.4 on 2023-08-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_member_image_alter_member_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="image",
            field=models.ImageField(upload_to="upload/"),
        ),
    ]
