# Generated by Django 4.2.4 on 2023-08-14 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_attendance_balance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="M_Shanmukha_Vardhan",
            new_name="Shanmukha_Vardhan",
        ),
        migrations.RenameField(
            model_name="balance",
            old_name="M_Shanmukha_Vardhan",
            new_name="Shanmukha_Vardhan",
        ),
    ]
