# Generated by Django 4.2.4 on 2023-08-14 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "members",
            "0003_rename_m_shanmukha_vardhan_attendance_shanmukha_vardhan_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="Chirag_Shanmukh",
            new_name="Chirag",
        ),
        migrations.RenameField(
            model_name="balance",
            old_name="Chirag_Shanmukh",
            new_name="Chirag",
        ),
    ]
