# Generated by Django 4.2.4 on 2023-08-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_rename_chirag_shanmukh_attendance_chirag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="balance",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
